### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by alanef** [bomsn/wp-plugin-rank#1]
Notice: Undefined property: stdClass::$downloaded in /Users/alanfuller/Local Sites/testwp/app/public/wp-content/plugins/wp-plugin-rank-master/includes/templates/plugin-details.php on line 22
 
 

# | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0008 | 371144 | {main}( ) | .../tools.php:0
2 | 0.0008 | 372392 | require_once(&nbsp;'/Users/alanfuller/Local Sites/testwp/app/public/wp-admin/admin.php'&nbsp;) | .../tools.php:40
3 | 0.3303 | 5843560 | do_action( ) | .../admin.php:259
4 | 0.3303 | 5843936 | WP_Hook-&gt;do_action( ) | .../plugin.php:470
5 | 0.3303 | 5843936 | WP_Hook-&gt;apply_filters( ) | .../class-wp-hook.php:327
6 | 0.3303 | 5845064 | WP_Plugin_Rank-&gt;plugin_rank_details( ) | .../class-wp-hook.php:303
7 | 0.7872 | 5944592 | wppr_display_plugin_data( ) | .../class-wp-plugin-rank.php:106
8 | 0.7872 | 5944592 | wppr_get_template( ) | .../helper-functions.php:43
9 | 0.7877 | 5944752 | load_template( ) | .../helper-functions.php:211
10 | 0.7883 | 5945488 | require_once(&nbsp;'/Users/alanfuller/Local Sites/testwp/app/public/wp-content/plugins/wp-plugin-rank-master/includes/templates/plugin-details.php'&nbsp;) | .../template.php:770

**Comment by bomsn** [comment]
Hello,
This may appear when the plugin doesn't report any downloads from the API, I added a check to fix the issue.

**Comment by alanef** [comment]
Thanks but strange as the plugin I was testing with had downloads.

**Comment by bomsn** [comment]
It's possible if the number of downloads is low, the API reports different number than the one appearing in the plugin stats area. But, will be happy to test if you can forward the slug

**Comment by bomsn** [comment]
I just checked and it seems the the API itself is not retuning download count for some plugins, not sure of the reason.
