### ISSUE TITLE
Rank position

### ISSUE THREAD

**Issue by alanef** [bomsn/wp-plugin-rank#2]
Maybe a counting error

Rank shown as 31  actual when counted manually = 15

Ranks shown as 41 actual when counted manually =  24

**Comment by bomsn** [comment]
Hello Alan,
Rank is based on the results from https://wordpress.org/plugins/, are you comparing to the same source or somewhere else?
It would be great to have the plugin slug so I can try to replicate and fix the issue.

Thanks,
Ali

**Comment by alanef** [comment]
I'm just manually counting the position of https://wordpress.org/plugins/search/anti-spam/  which is the same as putting the keyword anti-spam in add plugin - and I would have thought should be the same as the API

slug fullworks-anti-spam

**Comment by bomsn** [comment]
Fixed, it was a small bug in the code block responsible for calculating the plugin position.
Thanks
